/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_platforms_WindowsBinaryUtils */

#ifndef _Included_org_swdc_platforms_WindowsBinaryUtils
#define _Included_org_swdc_platforms_WindowsBinaryUtils
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_swdc_platforms_WindowsBinaryUtils
	 * Method:    dllRegisterServer
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_swdc_platforms_WindowsBinaryUtils_dllRegisterServer
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     org_swdc_platforms_WindowsBinaryUtils
	 * Method:    dllUnRegisterServer
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_swdc_platforms_WindowsBinaryUtils_dllUnRegisterServer
	(JNIEnv*, jclass, jstring);


	/*
	 * Class:     org_swdc_platforms_WindowsBinaryUtils
	 * Method:    getSystemDNSAddress
	 * Signature: ()[Ljava/lang/String;
	 */
	JNIEXPORT jobjectArray JNICALL Java_org_swdc_platforms_WindowsBinaryUtils_getSystemDNSAddress
	(JNIEnv*, jclass);
#ifdef __cplusplus
}
#endif
#endif
