/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_swdc_extern_ice_RegistryKey */

#ifndef _Included_org_swdc_extern_ice_RegistryKey
#define _Included_org_swdc_extern_ice_RegistryKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    openSubKey
 * Signature: (Ljava/lang/String;I)Lcom/ice/jni/registry/RegistryKey;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_extern_ice_RegistryKey_openSubKey
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    connectRegistry
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/ice/jni/registry/RegistryKey;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_extern_ice_RegistryKey_connectRegistry
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    createSubKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lcom/ice/jni/registry/RegistryKey;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_extern_ice_RegistryKey_createSubKey
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    closeKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_swdc_extern_ice_RegistryKey_closeKey
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    deleteSubKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_extern_ice_RegistryKey_deleteSubKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    deleteValue
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_extern_ice_RegistryKey_deleteValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    flushKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_swdc_extern_ice_RegistryKey_flushKey
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    getValue
 * Signature: (Ljava/lang/String;)Lcom/ice/jni/registry/RegistryValue;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_extern_ice_RegistryKey_getValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    setValue
 * Signature: (Ljava/lang/String;Lcom/ice/jni/registry/RegistryValue;)Z
 */
JNIEXPORT void JNICALL Java_org_swdc_extern_ice_RegistryKey_setValue
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    getStringValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_extern_ice_RegistryKey_getStringValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    getDefaultValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_extern_ice_RegistryKey_getDefaultValue
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    hasDefaultValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_extern_ice_RegistryKey_hasDefaultValue
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    hasOnlyDefaultValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_extern_ice_RegistryKey_hasOnlyDefaultValue
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    getNumberSubkeys
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_extern_ice_RegistryKey_getNumberSubkeys
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    getMaxSubkeyLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_extern_ice_RegistryKey_getMaxSubkeyLength
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    regEnumKey
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_extern_ice_RegistryKey_regEnumKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    getNumberValues
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_extern_ice_RegistryKey_getNumberValues
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    getMaxValueDataLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_extern_ice_RegistryKey_getMaxValueDataLength
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    getMaxValueNameLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_extern_ice_RegistryKey_getMaxValueNameLength
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    regEnumValue
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_extern_ice_RegistryKey_regEnumValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    incrDoubleWord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_extern_ice_RegistryKey_incrDoubleWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    decrDoubleWord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_extern_ice_RegistryKey_decrDoubleWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_extern_ice_RegistryKey
 * Method:    expandEnvStrings
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_extern_ice_RegistryKey_expandEnvStrings
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
